environment:
  base_path: 'https://updates.com'
updates:
  stable:
    version: '1.0.0'
    notes: 'Some feature added'
    pub_date: '2013-09-18'
  beta:
    version: '0.0.1'
    notes: 'Some feature added'
    pub_date: '2013-09-18'
